# .tmplr.yml
steps:
  - read: project_name
    from: env.repo_name
    fallback:
      from: path.rootdir

  - read: remote_provider
    from: env.server_url

  - read: remote_owner
    from: env.owner

  - read: clone_url
    from: git.remote_url

  - update: render.yaml
  - update: readme.md
  - update: Dockerfile
  - update: Cargo.toml
  - update: .env
  - update: configuration/base.yaml
  - update: src/main.rs
  - update: tests/api/sample_test.rs
  - update: tests/api/helper.rs
  - remove: .tmplr.yml