services:
  #Prod API
  - type: web
    name: prod rust-service-template
    env: docker
    repo: github.com/rgarbi/rust-service-template
    branch: main
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: prod rust-service-template-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: prod rust-service-template-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: prod rust-service-template-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: prod rust-service-template-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod rust-service-template-db
          property: database
      - key: APP__APPLICATION__WEB_APP_HOST
        value: https://SOME_APP_WEB_HOST.COM
      - key: APP__AUTH_CONFIG__AUDIENCE
        value: https://SOME_AUTH_CONFIG_AUDIENCE.COM
      - key: APP__AUTH_CONFIG__ISSUER
        value: https://SOME_AUTH_CONFIG_ISSUER
      - key: APP__AUTH_CONFIG__SIGNING_KEY
        generateValue: true
      - key: APP__EMAIL_CLIENT__API_KEY
        sync: false
      - key: APP__EMAIL_CLIENT__BASE_URL
        value: https://api.sendgrid.com
      - key: APP__EMAIL_CLIENT__SENDER_EMAIL
        value: EMAIL_CLIENT_SENDER_EMAil

  #STAGING API
  - type: web
    name: staging rust-service-template
    env: docker
    repo: github.com/rgarbi/rust-service-template
    branch: staging
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: staging rust-service-template-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: staging rust-service-template-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: staging rust-service-template-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: staging rust-service-template-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: staging rust-service-template-db
          property: database
      - key: APP__APPLICATION__WEB_APP_HOST
        value: https://SOME_APP_WEB_HOST.COM
      - key: APP__AUTH_CONFIG__AUDIENCE
        value: https://SOME_AUTH_CONFIG_AUDIENCE.COM
      - key: APP__AUTH_CONFIG__ISSUER
        value: https://SOME_AUTH_CONFIG_ISSUER
      - key: APP__AUTH_CONFIG__SIGNING_KEY
        generateValue: true
      - key: APP__EMAIL_CLIENT__API_KEY
        sync: false
      - key: APP__EMAIL_CLIENT__BASE_URL
        value: https://api.sendgrid.com
      - key: APP__EMAIL_CLIENT__SENDER_EMAIL
        value: EMAIL_CLIENT_SENDER_EMAil

databases:
  - name: prod rust-service-template-db
    plan: starter
    region: oregon
    databaseName: prod_rust-service-template_db
  - name: staging rust-service-template-db
    plan: starter
    region: oregon
    databaseName: staging_rust-service-template_db
